name: Deploy to Local Server

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build_deploy:
    runs-on: self-hosted

    steps:
      # Шаг 1: Раннер на твоем ПК скачивает свежий код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Твой ПК собирает Docker-образ
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag financialassistentbot:latest

      # Шаг 3: Твой ПК останавливает и удаляет старый контейнер
      - name: Stop and remove old container
        run: |
          docker stop finassistbot || true
          docker rm finassistbot || true

      # Шаг 4: Твой ПК запускает новый контейнер с подтягиванием секретов из GitHub
      - name: Run new container
        run: |
          docker run -d --name finassistbot \
            --restart unless-stopped \
            -e AI_TOKEN_POLZA="${{ secrets.AI_TOKEN_POLZA }}" \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e TG_TOKEN="${{ secrets.TG_TOKEN }}" \
            financialassistentbot:latest
